# Generated by Django 5.0.6 on 2024-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата создания записи"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="preview/", verbose_name="Превью"
            ),
        ),
    ]
