# Generated by Django 5.0.6 on 2024-05-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date_creation",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Date_last_changes",
            new_name="updated_at",
        ),
    ]
