# Generated by Django 4.2 on 2024-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creator",
            field=models.TextField(blank=True, null=True, verbose_name="Создатель"),
        ),
    ]
